packages:
  - apps/*
  - packages/*
  - tooling
patchedDependencies:
  '@react-pdf/textkit@6.3.0': patches/@react-pdf__textkit@6.3.0.patch
minimumReleaseAge: 0
allowBuilds:
  bcrypt: true
  esbuild: true
  lefthook: true
  msgpackr-extract: true
  msw: true
  sharp: true
overrides:
  esbuild@>=0.17.0 <0.28.1: ^0.28.1
  esbuild@>=0.27.3 <0.28.1: ^0.28.1
  postcss@<8.5.10: ^8.5.14
  samlify@<2.13.0: ^2.13.0
  uuid@<11.1.1: ^11.1.1
