/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as HomeRouteRouteImport } from "./routes/_home/route";
import { Route as AuthRouteRouteImport } from "./routes/auth/route";
import { Route as DashboardRouteRouteImport } from "./routes/dashboard/route";
import { Route as UsernameSlugRouteImport } from "./routes/$username/$slug";
import { Route as HomeIndexRouteImport } from "./routes/_home/index";
import { Route as AuthIndexRouteImport } from "./routes/auth/index";
import { Route as AuthConsentRouteImport } from "./routes/auth/consent";
import { Route as AuthErrorRouteImport } from "./routes/auth/error";
import { Route as AuthForgotPasswordRouteImport } from "./routes/auth/forgot-password";
import { Route as AuthLoginRouteImport } from "./routes/auth/login";
import { Route as AuthRegisterRouteImport } from "./routes/auth/register";
import { Route as AuthResetPasswordRouteImport } from "./routes/auth/reset-password";
import { Route as AuthResumePasswordRouteImport } from "./routes/auth/resume-password";
import { Route as AuthVerify2faRouteImport } from "./routes/auth/verify-2fa";
import { Route as AuthVerify2faBackupRouteImport } from "./routes/auth/verify-2fa-backup";
import { Route as BuilderResumeIdRouteRouteImport } from "./routes/builder/$resumeId/route";
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index";
import { Route as DashboardCoverLettersRouteImport } from "./routes/dashboard/cover-letters";
import { Route as DashboardSettingsRouteRouteImport } from "./routes/dashboard/settings/route";
import { Route as DashboardTrashRouteImport } from "./routes/dashboard/trash";
import { Route as BuilderResumeIdIndexRouteImport } from "./routes/builder/$resumeId/index";
import { Route as BuilderLetterCoverLetterIdRouteImport } from "./routes/builder/letter/$coverLetterId";
import { Route as DashboardApplicationsIndexRouteImport } from "./routes/dashboard/applications/index";
import { Route as DashboardResumesIndexRouteImport } from "./routes/dashboard/resumes/index";
import { Route as DashboardSettingsIndexRouteImport } from "./routes/dashboard/settings/index";
import { Route as DashboardSettingsAccountRouteImport } from "./routes/dashboard/settings/account";
import { Route as DashboardSettingsAiRouteImport } from "./routes/dashboard/settings/ai";
import { Route as DashboardSettingsApiKeysRouteImport } from "./routes/dashboard/settings/api-keys";
import { Route as DashboardSettingsIntegrationsRouteRouteImport } from "./routes/dashboard/settings/integrations/route";
import { Route as DashboardSettingsPreferencesRouteImport } from "./routes/dashboard/settings/preferences";
import { Route as DashboardSettingsProfileRouteImport } from "./routes/dashboard/settings/profile";
import { Route as DashboardSettingsAuthenticationIndexRouteImport } from "./routes/dashboard/settings/authentication/index";

const HomeRouteRoute = HomeRouteRouteImport.update({
  id: "/_home",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const UsernameSlugRoute = UsernameSlugRouteImport.update({
  id: "/$username/$slug",
  path: "/$username/$slug",
  getParentRoute: () => rootRouteImport,
} as any);
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => HomeRouteRoute,
} as any);
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthConsentRoute = AuthConsentRouteImport.update({
  id: "/consent",
  path: "/consent",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: "/error",
  path: "/error",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthResumePasswordRoute = AuthResumePasswordRouteImport.update({
  id: "/resume-password",
  path: "/resume-password",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthVerify2faRoute = AuthVerify2faRouteImport.update({
  id: "/verify-2fa",
  path: "/verify-2fa",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthVerify2faBackupRoute = AuthVerify2faBackupRouteImport.update({
  id: "/verify-2fa-backup",
  path: "/verify-2fa-backup",
  getParentRoute: () => AuthRouteRoute,
} as any);
const BuilderResumeIdRouteRoute = BuilderResumeIdRouteRouteImport.update({
  id: "/builder/$resumeId",
  path: "/builder/$resumeId",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardCoverLettersRoute = DashboardCoverLettersRouteImport.update({
  id: "/cover-letters",
  path: "/cover-letters",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardTrashRoute = DashboardTrashRouteImport.update({
  id: "/trash",
  path: "/trash",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const BuilderResumeIdIndexRoute = BuilderResumeIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => BuilderResumeIdRouteRoute,
} as any);
const BuilderLetterCoverLetterIdRoute =
  BuilderLetterCoverLetterIdRouteImport.update({
    id: "/builder/letter/$coverLetterId",
    path: "/builder/letter/$coverLetterId",
    getParentRoute: () => rootRouteImport,
  } as any);
const DashboardApplicationsIndexRoute =
  DashboardApplicationsIndexRouteImport.update({
    id: "/applications/",
    path: "/applications/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardResumesIndexRoute = DashboardResumesIndexRouteImport.update({
  id: "/resumes/",
  path: "/resumes/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any);
const DashboardSettingsAccountRoute =
  DashboardSettingsAccountRouteImport.update({
    id: "/account",
    path: "/account",
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any);
const DashboardSettingsAiRoute = DashboardSettingsAiRouteImport.update({
  id: "/ai",
  path: "/ai",
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any);
const DashboardSettingsApiKeysRoute =
  DashboardSettingsApiKeysRouteImport.update({
    id: "/api-keys",
    path: "/api-keys",
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any);
const DashboardSettingsIntegrationsRouteRoute =
  DashboardSettingsIntegrationsRouteRouteImport.update({
    id: "/integrations",
    path: "/integrations",
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any);
const DashboardSettingsPreferencesRoute =
  DashboardSettingsPreferencesRouteImport.update({
    id: "/preferences",
    path: "/preferences",
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any);
const DashboardSettingsProfileRoute =
  DashboardSettingsProfileRouteImport.update({
    id: "/profile",
    path: "/profile",
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any);
const DashboardSettingsAuthenticationIndexRoute =
  DashboardSettingsAuthenticationIndexRouteImport.update({
    id: "/authentication/",
    path: "/authentication/",
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof HomeIndexRoute;
  "/auth": typeof AuthRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/builder/$resumeId": typeof BuilderResumeIdRouteRouteWithChildren;
  "/dashboard/settings": typeof DashboardSettingsRouteRouteWithChildren;
  "/$username/$slug": typeof UsernameSlugRoute;
  "/auth/consent": typeof AuthConsentRoute;
  "/auth/error": typeof AuthErrorRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/register": typeof AuthRegisterRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/auth/resume-password": typeof AuthResumePasswordRoute;
  "/auth/verify-2fa": typeof AuthVerify2faRoute;
  "/auth/verify-2fa-backup": typeof AuthVerify2faBackupRoute;
  "/dashboard/cover-letters": typeof DashboardCoverLettersRoute;
  "/dashboard/trash": typeof DashboardTrashRoute;
  "/auth/": typeof AuthIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/dashboard/settings/integrations": typeof DashboardSettingsIntegrationsRouteRoute;
  "/builder/letter/$coverLetterId": typeof BuilderLetterCoverLetterIdRoute;
  "/dashboard/settings/account": typeof DashboardSettingsAccountRoute;
  "/dashboard/settings/ai": typeof DashboardSettingsAiRoute;
  "/dashboard/settings/api-keys": typeof DashboardSettingsApiKeysRoute;
  "/dashboard/settings/preferences": typeof DashboardSettingsPreferencesRoute;
  "/dashboard/settings/profile": typeof DashboardSettingsProfileRoute;
  "/builder/$resumeId/": typeof BuilderResumeIdIndexRoute;
  "/dashboard/applications/": typeof DashboardApplicationsIndexRoute;
  "/dashboard/resumes/": typeof DashboardResumesIndexRoute;
  "/dashboard/settings/": typeof DashboardSettingsIndexRoute;
  "/dashboard/settings/authentication/": typeof DashboardSettingsAuthenticationIndexRoute;
}
export interface FileRoutesByTo {
  "/$username/$slug": typeof UsernameSlugRoute;
  "/auth/consent": typeof AuthConsentRoute;
  "/auth/error": typeof AuthErrorRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/register": typeof AuthRegisterRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/auth/resume-password": typeof AuthResumePasswordRoute;
  "/auth/verify-2fa": typeof AuthVerify2faRoute;
  "/auth/verify-2fa-backup": typeof AuthVerify2faBackupRoute;
  "/dashboard/cover-letters": typeof DashboardCoverLettersRoute;
  "/dashboard/trash": typeof DashboardTrashRoute;
  "/": typeof HomeIndexRoute;
  "/auth": typeof AuthIndexRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/dashboard/settings/integrations": typeof DashboardSettingsIntegrationsRouteRoute;
  "/builder/letter/$coverLetterId": typeof BuilderLetterCoverLetterIdRoute;
  "/dashboard/settings/account": typeof DashboardSettingsAccountRoute;
  "/dashboard/settings/ai": typeof DashboardSettingsAiRoute;
  "/dashboard/settings/api-keys": typeof DashboardSettingsApiKeysRoute;
  "/dashboard/settings/preferences": typeof DashboardSettingsPreferencesRoute;
  "/dashboard/settings/profile": typeof DashboardSettingsProfileRoute;
  "/builder/$resumeId": typeof BuilderResumeIdIndexRoute;
  "/dashboard/applications": typeof DashboardApplicationsIndexRoute;
  "/dashboard/resumes": typeof DashboardResumesIndexRoute;
  "/dashboard/settings": typeof DashboardSettingsIndexRoute;
  "/dashboard/settings/authentication": typeof DashboardSettingsAuthenticationIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_home": typeof HomeRouteRouteWithChildren;
  "/auth": typeof AuthRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/builder/$resumeId": typeof BuilderResumeIdRouteRouteWithChildren;
  "/dashboard/settings": typeof DashboardSettingsRouteRouteWithChildren;
  "/$username/$slug": typeof UsernameSlugRoute;
  "/auth/consent": typeof AuthConsentRoute;
  "/auth/error": typeof AuthErrorRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/register": typeof AuthRegisterRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/auth/resume-password": typeof AuthResumePasswordRoute;
  "/auth/verify-2fa": typeof AuthVerify2faRoute;
  "/auth/verify-2fa-backup": typeof AuthVerify2faBackupRoute;
  "/dashboard/cover-letters": typeof DashboardCoverLettersRoute;
  "/dashboard/trash": typeof DashboardTrashRoute;
  "/_home/": typeof HomeIndexRoute;
  "/auth/": typeof AuthIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/dashboard/settings/integrations": typeof DashboardSettingsIntegrationsRouteRoute;
  "/builder/letter/$coverLetterId": typeof BuilderLetterCoverLetterIdRoute;
  "/dashboard/settings/account": typeof DashboardSettingsAccountRoute;
  "/dashboard/settings/ai": typeof DashboardSettingsAiRoute;
  "/dashboard/settings/api-keys": typeof DashboardSettingsApiKeysRoute;
  "/dashboard/settings/preferences": typeof DashboardSettingsPreferencesRoute;
  "/dashboard/settings/profile": typeof DashboardSettingsProfileRoute;
  "/builder/$resumeId/": typeof BuilderResumeIdIndexRoute;
  "/dashboard/applications/": typeof DashboardApplicationsIndexRoute;
  "/dashboard/resumes/": typeof DashboardResumesIndexRoute;
  "/dashboard/settings/": typeof DashboardSettingsIndexRoute;
  "/dashboard/settings/authentication/": typeof DashboardSettingsAuthenticationIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/auth"
    | "/dashboard"
    | "/builder/$resumeId"
    | "/dashboard/settings"
    | "/$username/$slug"
    | "/auth/consent"
    | "/auth/error"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/register"
    | "/auth/reset-password"
    | "/auth/resume-password"
    | "/auth/verify-2fa"
    | "/auth/verify-2fa-backup"
    | "/dashboard/cover-letters"
    | "/dashboard/trash"
    | "/auth/"
    | "/dashboard/"
    | "/dashboard/settings/integrations"
    | "/builder/letter/$coverLetterId"
    | "/dashboard/settings/account"
    | "/dashboard/settings/ai"
    | "/dashboard/settings/api-keys"
    | "/dashboard/settings/preferences"
    | "/dashboard/settings/profile"
    | "/builder/$resumeId/"
    | "/dashboard/applications/"
    | "/dashboard/resumes/"
    | "/dashboard/settings/"
    | "/dashboard/settings/authentication/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/$username/$slug"
    | "/auth/consent"
    | "/auth/error"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/register"
    | "/auth/reset-password"
    | "/auth/resume-password"
    | "/auth/verify-2fa"
    | "/auth/verify-2fa-backup"
    | "/dashboard/cover-letters"
    | "/dashboard/trash"
    | "/"
    | "/auth"
    | "/dashboard"
    | "/dashboard/settings/integrations"
    | "/builder/letter/$coverLetterId"
    | "/dashboard/settings/account"
    | "/dashboard/settings/ai"
    | "/dashboard/settings/api-keys"
    | "/dashboard/settings/preferences"
    | "/dashboard/settings/profile"
    | "/builder/$resumeId"
    | "/dashboard/applications"
    | "/dashboard/resumes"
    | "/dashboard/settings"
    | "/dashboard/settings/authentication";
  id:
    | "__root__"
    | "/_home"
    | "/auth"
    | "/dashboard"
    | "/builder/$resumeId"
    | "/dashboard/settings"
    | "/$username/$slug"
    | "/auth/consent"
    | "/auth/error"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/register"
    | "/auth/reset-password"
    | "/auth/resume-password"
    | "/auth/verify-2fa"
    | "/auth/verify-2fa-backup"
    | "/dashboard/cover-letters"
    | "/dashboard/trash"
    | "/_home/"
    | "/auth/"
    | "/dashboard/"
    | "/dashboard/settings/integrations"
    | "/builder/letter/$coverLetterId"
    | "/dashboard/settings/account"
    | "/dashboard/settings/ai"
    | "/dashboard/settings/api-keys"
    | "/dashboard/settings/preferences"
    | "/dashboard/settings/profile"
    | "/builder/$resumeId/"
    | "/dashboard/applications/"
    | "/dashboard/resumes/"
    | "/dashboard/settings/"
    | "/dashboard/settings/authentication/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  HomeRouteRoute: typeof HomeRouteRouteWithChildren;
  AuthRouteRoute: typeof AuthRouteRouteWithChildren;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
  BuilderResumeIdRouteRoute: typeof BuilderResumeIdRouteRouteWithChildren;
  UsernameSlugRoute: typeof UsernameSlugRoute;
  BuilderLetterCoverLetterIdRoute: typeof BuilderLetterCoverLetterIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_home": {
      id: "/_home";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof HomeRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth": {
      id: "/auth";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof AuthRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$username/$slug": {
      id: "/$username/$slug";
      path: "/$username/$slug";
      fullPath: "/$username/$slug";
      preLoaderRoute: typeof UsernameSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_home/": {
      id: "/_home/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof HomeIndexRouteImport;
      parentRoute: typeof HomeRouteRoute;
    };
    "/auth/": {
      id: "/auth/";
      path: "/";
      fullPath: "/auth/";
      preLoaderRoute: typeof AuthIndexRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/consent": {
      id: "/auth/consent";
      path: "/consent";
      fullPath: "/auth/consent";
      preLoaderRoute: typeof AuthConsentRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/error": {
      id: "/auth/error";
      path: "/error";
      fullPath: "/auth/error";
      preLoaderRoute: typeof AuthErrorRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/forgot-password": {
      id: "/auth/forgot-password";
      path: "/forgot-password";
      fullPath: "/auth/forgot-password";
      preLoaderRoute: typeof AuthForgotPasswordRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/login": {
      id: "/auth/login";
      path: "/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/register": {
      id: "/auth/register";
      path: "/register";
      fullPath: "/auth/register";
      preLoaderRoute: typeof AuthRegisterRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/reset-password": {
      id: "/auth/reset-password";
      path: "/reset-password";
      fullPath: "/auth/reset-password";
      preLoaderRoute: typeof AuthResetPasswordRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/resume-password": {
      id: "/auth/resume-password";
      path: "/resume-password";
      fullPath: "/auth/resume-password";
      preLoaderRoute: typeof AuthResumePasswordRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/verify-2fa": {
      id: "/auth/verify-2fa";
      path: "/verify-2fa";
      fullPath: "/auth/verify-2fa";
      preLoaderRoute: typeof AuthVerify2faRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/verify-2fa-backup": {
      id: "/auth/verify-2fa-backup";
      path: "/verify-2fa-backup";
      fullPath: "/auth/verify-2fa-backup";
      preLoaderRoute: typeof AuthVerify2faBackupRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/builder/$resumeId": {
      id: "/builder/$resumeId";
      path: "/builder/$resumeId";
      fullPath: "/builder/$resumeId";
      preLoaderRoute: typeof BuilderResumeIdRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/cover-letters": {
      id: "/dashboard/cover-letters";
      path: "/cover-letters";
      fullPath: "/dashboard/cover-letters";
      preLoaderRoute: typeof DashboardCoverLettersRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings": {
      id: "/dashboard/settings";
      path: "/settings";
      fullPath: "/dashboard/settings";
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/trash": {
      id: "/dashboard/trash";
      path: "/trash";
      fullPath: "/dashboard/trash";
      preLoaderRoute: typeof DashboardTrashRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/builder/$resumeId/": {
      id: "/builder/$resumeId/";
      path: "/";
      fullPath: "/builder/$resumeId/";
      preLoaderRoute: typeof BuilderResumeIdIndexRouteImport;
      parentRoute: typeof BuilderResumeIdRouteRoute;
    };
    "/builder/letter/$coverLetterId": {
      id: "/builder/letter/$coverLetterId";
      path: "/builder/letter/$coverLetterId";
      fullPath: "/builder/letter/$coverLetterId";
      preLoaderRoute: typeof BuilderLetterCoverLetterIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/applications/": {
      id: "/dashboard/applications/";
      path: "/applications";
      fullPath: "/dashboard/applications/";
      preLoaderRoute: typeof DashboardApplicationsIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/resumes/": {
      id: "/dashboard/resumes/";
      path: "/resumes";
      fullPath: "/dashboard/resumes/";
      preLoaderRoute: typeof DashboardResumesIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings/": {
      id: "/dashboard/settings/";
      path: "/";
      fullPath: "/dashboard/settings/";
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport;
      parentRoute: typeof DashboardSettingsRouteRoute;
    };
    "/dashboard/settings/account": {
      id: "/dashboard/settings/account";
      path: "/account";
      fullPath: "/dashboard/settings/account";
      preLoaderRoute: typeof DashboardSettingsAccountRouteImport;
      parentRoute: typeof DashboardSettingsRouteRoute;
    };
    "/dashboard/settings/ai": {
      id: "/dashboard/settings/ai";
      path: "/ai";
      fullPath: "/dashboard/settings/ai";
      preLoaderRoute: typeof DashboardSettingsAiRouteImport;
      parentRoute: typeof DashboardSettingsRouteRoute;
    };
    "/dashboard/settings/api-keys": {
      id: "/dashboard/settings/api-keys";
      path: "/api-keys";
      fullPath: "/dashboard/settings/api-keys";
      preLoaderRoute: typeof DashboardSettingsApiKeysRouteImport;
      parentRoute: typeof DashboardSettingsRouteRoute;
    };
    "/dashboard/settings/integrations": {
      id: "/dashboard/settings/integrations";
      path: "/integrations";
      fullPath: "/dashboard/settings/integrations";
      preLoaderRoute: typeof DashboardSettingsIntegrationsRouteRouteImport;
      parentRoute: typeof DashboardSettingsRouteRoute;
    };
    "/dashboard/settings/preferences": {
      id: "/dashboard/settings/preferences";
      path: "/preferences";
      fullPath: "/dashboard/settings/preferences";
      preLoaderRoute: typeof DashboardSettingsPreferencesRouteImport;
      parentRoute: typeof DashboardSettingsRouteRoute;
    };
    "/dashboard/settings/profile": {
      id: "/dashboard/settings/profile";
      path: "/profile";
      fullPath: "/dashboard/settings/profile";
      preLoaderRoute: typeof DashboardSettingsProfileRouteImport;
      parentRoute: typeof DashboardSettingsRouteRoute;
    };
    "/dashboard/settings/authentication/": {
      id: "/dashboard/settings/authentication/";
      path: "/authentication";
      fullPath: "/dashboard/settings/authentication/";
      preLoaderRoute: typeof DashboardSettingsAuthenticationIndexRouteImport;
      parentRoute: typeof DashboardSettingsRouteRoute;
    };
  }
}

interface HomeRouteRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute;
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
};

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
);

interface AuthRouteRouteChildren {
  AuthConsentRoute: typeof AuthConsentRoute;
  AuthErrorRoute: typeof AuthErrorRoute;
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthRegisterRoute: typeof AuthRegisterRoute;
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute;
  AuthResumePasswordRoute: typeof AuthResumePasswordRoute;
  AuthVerify2faRoute: typeof AuthVerify2faRoute;
  AuthVerify2faBackupRoute: typeof AuthVerify2faBackupRoute;
  AuthIndexRoute: typeof AuthIndexRoute;
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthConsentRoute: AuthConsentRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthResumePasswordRoute: AuthResumePasswordRoute,
  AuthVerify2faRoute: AuthVerify2faRoute,
  AuthVerify2faBackupRoute: AuthVerify2faBackupRoute,
  AuthIndexRoute: AuthIndexRoute,
};

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
);

interface DashboardSettingsRouteRouteChildren {
  DashboardSettingsIntegrationsRouteRoute: typeof DashboardSettingsIntegrationsRouteRoute;
  DashboardSettingsAccountRoute: typeof DashboardSettingsAccountRoute;
  DashboardSettingsAiRoute: typeof DashboardSettingsAiRoute;
  DashboardSettingsApiKeysRoute: typeof DashboardSettingsApiKeysRoute;
  DashboardSettingsPreferencesRoute: typeof DashboardSettingsPreferencesRoute;
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute;
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute;
  DashboardSettingsAuthenticationIndexRoute: typeof DashboardSettingsAuthenticationIndexRoute;
}

const DashboardSettingsRouteRouteChildren: DashboardSettingsRouteRouteChildren =
  {
    DashboardSettingsIntegrationsRouteRoute:
      DashboardSettingsIntegrationsRouteRoute,
    DashboardSettingsAccountRoute: DashboardSettingsAccountRoute,
    DashboardSettingsAiRoute: DashboardSettingsAiRoute,
    DashboardSettingsApiKeysRoute: DashboardSettingsApiKeysRoute,
    DashboardSettingsPreferencesRoute: DashboardSettingsPreferencesRoute,
    DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
    DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
    DashboardSettingsAuthenticationIndexRoute:
      DashboardSettingsAuthenticationIndexRoute,
  };

const DashboardSettingsRouteRouteWithChildren =
  DashboardSettingsRouteRoute._addFileChildren(
    DashboardSettingsRouteRouteChildren,
  );

interface DashboardRouteRouteChildren {
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRouteWithChildren;
  DashboardCoverLettersRoute: typeof DashboardCoverLettersRoute;
  DashboardTrashRoute: typeof DashboardTrashRoute;
  DashboardIndexRoute: typeof DashboardIndexRoute;
  DashboardApplicationsIndexRoute: typeof DashboardApplicationsIndexRoute;
  DashboardResumesIndexRoute: typeof DashboardResumesIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSettingsRouteRoute: DashboardSettingsRouteRouteWithChildren,
  DashboardCoverLettersRoute: DashboardCoverLettersRoute,
  DashboardTrashRoute: DashboardTrashRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardApplicationsIndexRoute: DashboardApplicationsIndexRoute,
  DashboardResumesIndexRoute: DashboardResumesIndexRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

interface BuilderResumeIdRouteRouteChildren {
  BuilderResumeIdIndexRoute: typeof BuilderResumeIdIndexRoute;
}

const BuilderResumeIdRouteRouteChildren: BuilderResumeIdRouteRouteChildren = {
  BuilderResumeIdIndexRoute: BuilderResumeIdIndexRoute,
};

const BuilderResumeIdRouteRouteWithChildren =
  BuilderResumeIdRouteRoute._addFileChildren(BuilderResumeIdRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  HomeRouteRoute: HomeRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  BuilderResumeIdRouteRoute: BuilderResumeIdRouteRouteWithChildren,
  UsernameSlugRoute: UsernameSlugRoute,
  BuilderLetterCoverLetterIdRoute: BuilderLetterCoverLetterIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
