/** Canonical MCP tool names. */
export const MCP_TOOL_NAME = {
	listResumes: "list_resumes",
	listResumeTags: "list_resume_tags",
	getResume: "read_resume",
	getResumeAnalysis: "get_resume_analysis",
	downloadResumePdf: "download_resume_pdf",
	createResume: "create_resume",
	importResume: "import_resume",
	duplicateResume: "duplicate_resume",
	patchResume: "apply_resume_patch",
	updateResume: "update_resume",
	deleteResume: "delete_resume",
	lockResume: "lock_resume",
	unlockResume: "unlock_resume",
	getResumeStatistics: "get_resume_statistics",
	listApplications: "list_applications",
	readApplication: "read_application",
	listApplicationTags: "list_application_tags",
	getApplicationStats: "get_application_stats",
	createApplication: "create_application",
	updateApplication: "update_application",
	addApplicationNote: "add_application_note",
	updateApplicationTimelineEntry: "update_application_timeline_entry",
	deleteApplicationTimelineEntry: "delete_application_timeline_entry",
	deleteApplication: "delete_application",
	bulkUpdateApplications: "bulk_update_applications",
	bulkDeleteApplications: "bulk_delete_applications",
	importApplications: "import_applications",
	attachApplicationDocument: "attach_application_document",
	removeApplicationDocument: "remove_application_document",
	autofillApplicationFromJob: "autofill_application_from_job",
	scoreApplicationMatch: "score_application_match",
	tailorResumeForApplication: "tailor_resume_for_application",
	draftApplicationMessage: "draft_application_message",
} as const;
