import type iconData from "./phosphor-icons.json";
import type { StyleProp } from "./style-types";
import { Svg } from "./primitives";
import { flattenStyle, toColor } from "./style";

/** A Phosphor icon name, e.g. "address-book". */
export type IconName = keyof typeof iconData;

let icons: Record<string, string> | undefined;
let loading: Promise<void> | undefined;

/**
 * Loads the icon drawings (generated by `pnpm --filter @reactive-resume/tooling icons:pdf`). They're 190 KB
 * gzipped, so they arrive with the first render rather than with the app.
 */
export const loadIcons = () =>
	(loading ??= import("./phosphor-icons.json").then((module) => {
		icons = module.default as Record<string, string>;
	}));

type PhosphorIconProps = {
	name: IconName | string;
	size?: number | string | undefined;
	color?: string | undefined;
	opacity?: number | string | undefined;
	/** "none" hides the icon, as on react-pdf's SVG. */
	display?: "none" | "flex" | undefined;
	style?: StyleProp | undefined;
	weight?: "regular" | undefined;
};

/**
 * A regular-weight Phosphor icon, drawn as vector paths. Same props as `phosphor-icons-react-pdf`'s `Icon`; an
 * unknown name draws nothing.
 */
export function PhosphorIcon({ name, size = 16, color = "currentColor", opacity, display, style }: PhosphorIconProps) {
	const markup = icons?.[name];
	if (!markup || display === "none") return null;
	// "currentColor" means the colour the template set on the icon's style, as in react-pdf.
	const { opacity: styleOpacity, ...flat } = flattenStyle(style);
	// Forme 0.25 lets an SVG's opacity leak into whatever it draws next, so it goes into the paint instead.
	const alpha = Number(opacity ?? styleOpacity ?? 1);
	const paint = svgPaint(
		color === "currentColor" ? (flat.color ?? "#000000") : color,
		Number.isFinite(alpha) ? alpha : 1,
	);
	return (
		<Svg
			viewBox="0 0 256 256"
			width={size}
			height={size}
			content={markup.replaceAll("<path ", `<path ${paint} `)}
			style={flat}
		/>
	);
}

/** SVG fill attributes for a CSS colour: hex, with rgba's alpha times `opacity` as `fill-opacity`. */
function svgPaint(color: string, opacity: number) {
	const parsed = toColor(color) ?? "#000000";
	const match = /^rgba?\(([^)]*)\)$/i.exec(parsed);
	const [r = 0, g = 0, b = 0, a = 1] = match?.[1] ? match[1].split(/\s*,\s*/).map(Number) : [];
	const hex = match
		? `#${[r, g, b].map((channel) => Math.round(channel).toString(16).padStart(2, "0")).join("")}`
		: parsed;
	const alpha = a * opacity;
	return alpha < 1 ? `fill="${hex}" fill-opacity="${alpha}"` : `fill="${hex}"`;
}
